Add microsoft-oauth example
Web3Auth/web3auth-pnp-examples pull request #913
Opened 2024-03-05 01:04 UTC by rtomas

+ example
+ readme
+ and guide in docs repository

2024-03-05 04:27 UTC, shahbaz17 requested changes

2024-03-05 04:27 UTC, shahbaz17 commented on web3auth-byoa/microsoft-oauth-connection/README.md
> +Open your browser and navigate to http://localhost:5005/ms/login to initiate the Microsoft OAuth flow.
Please wrap it inside ``, e.g.`http://localhost:5005/ms/login`

2024-03-06 02:31 UTC, AyushBherwani1998 approved these changes

2024-03-06 02:38 UTC, shahbaz17 approved these changes

2024-03-06 12:51 UTC, merged